E2E Testing
iot-for-all/iotc-device-bridge pull request #10
Opened 2021-02-17 07:31 UTC by Jackbk-nz

Added E2E test app
Added E2E echo azure function

2021-02-26 01:52 UTC, peolivei2 requested changes

2021-02-26 01:52 UTC, peolivei2 commented on DeviceBridgeE2E/data/deviceTemplates/basic.json
> +                "@id": "dtmi:jeff:Basic8:temperature;1",
Can we replace the references to `jeff` by something else in this file? :D
(just replace the occurences by something like `test`)

2021-02-26 01:52 UTC, peolivei2 commented on DeviceBridgeE2E/EchoAzureFunction/DeviceBridgeE2EEcho/DeviceBridgeE2EEcho.cs
> +        static Dictionary<string, string> cache = new Dictionary<string, string>();
Can you switch to a `ConcurrentDictionary`? (IIRC az functions will spin up a new thread per request, so we might see some weird behaviors)

2021-02-26 01:52 UTC, peolivei2 commented on DeviceBridgeE2E/package-lock.json
> +{
Remove this package-lock file.

2021-02-26 01:52 UTC, peolivei2 commented on DeviceBridgeE2E/src/device-bridge.spec.ts
> +    t.is(response.body.status, "Running");
Might be a good idea to wait a bit here. It will take a few seconds before the bridge registers the device and the status changes to running.

2021-02-26 01:52 UTC, peolivei2 commented on DeviceBridgeE2E/src/device-bridge.spec.ts
> +    await t.context.ctx.publicAPI.executeCommand(t, t.context.device.id, "cmd");
Can you send some payload in the request body, to validate that the correct payload is sent to the subscription.

2021-02-26 01:52 UTC, peolivei2 commented on DeviceBridgeE2E/src/device-bridge.spec.ts
> +test.serial('Test device connection status callback', async t => {
Can you move this one to be the first test? (seems a more intuitive order having the connection status test first)

2021-02-26 01:52 UTC, peolivei2 commented on DeviceBridgeE2E/src/device-bridge.spec.ts
> +    const temperatureValue = 120;
Can you use a random value (to make sure we're not picking up the value of a previous test execution)

2021-02-26 01:52 UTC, peolivei2 commented on DeviceBridgeE2E/src/device-bridge.spec.ts
> +        await new Promise(r => setTimeout(r, 2000));
I think you have a utility for this :)

2021-02-26 01:52 UTC, peolivei2 commented on DeviceBridgeE2E/src/device-bridge.spec.ts
> +            "rwProp": "testValue",
Also use a random value here, tom make sure we're not reading the result of a previous execution.

2021-02-26 01:52 UTC, peolivei2 commented on DeviceBridgeE2E/src/device-bridge.spec.ts
> +import anyTest, { TestInterface } from 'ava';
Can you add test cases for:
- C2D message subscription
- Getting the current connection status (not the subscription, but the point-in-time one)

2021-02-26 01:52 UTC, peolivei2 commented on DeviceBridgeE2E/src/device-bridge.spec.ts
> +import anyTest, { TestInterface } from 'ava';
(just a placeholder comment so we don't forget to add auth tests)

2021-02-26 01:55 UTC, peolivei2 commented on DeviceBridgeE2E/src/device-bridge.spec.ts
> +import anyTest, { TestInterface } from 'ava';
(another placeholder to remember to add tests for the health endpoint)

2021-03-02 07:03 UTC, peolivei2 requested changes

2021-03-02 07:10 UTC, Jackbk-nz commented on DeviceBridgeE2E/src/device-bridge.spec.ts
> +    await t.context.ctx.deviceBridgAPI.createCMDSubscription(t, t.context.device.id, callbackUrl)
It should be... which begs the question why was is it passing

2021-03-03 19:31 UTC, peolivei2 commented on DeviceBridgeE2E/src/device-bridge.spec.ts
> +    await t.context.ctx.deviceBridgAPI.createCMDSubscription(t, t.context.device.id, callbackUrl)
Just for peace of mind, I'd try running with something that definitely should fail ,to make sure it's actually reporting it.

2021-03-03 22:21 UTC, peolivei2 approved these changes

2021-03-03 23:14 UTC, merged